SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `wework_tokens` (
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `access_token` VARCHAR(512) NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
